name: Deploy to Hugging Face Spaces

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Test application
      run: |
        python test_app.py
        
    - name: Deploy to Hugging Face Spaces
      if: github.ref == 'refs/heads/main'
      uses: huggingface/huggingface_hub@v0.20.3
      with:
        repo-type: space
        repo-id: ${{ secrets.HF_USERNAME }}/classical-cv
        token: ${{ secrets.HF_TOKEN }}
        space-sdk: gradio
        space-hardware: cpu-basic
        space-license: mit
        space-title: "Classical Computer Vision Algorithms"
        space-description: "Interactive web interface for testing classical computer vision algorithms"
        space-tags: "computer-vision,opencv,gradio,algorithms" 